spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/timebank
    username: root
    password: "tz777700"

server:
  port: 8080
mybatis:

